#!/bin/bash


#################
#print numbers from 1 to 100 div by 3 and 5 but not with 15
#################

for i in {1..100};do

	if ([`expr $i % 3` == 0 ] || [`expr $i % 5` == 0 ]) && [`expr $i % 15` != 0 ];
	then
		echo $i
	fi;
done

